version: "3.7"

services:
  postgresDB:
    container_name: postgresDB
    image: postgres:latest
    ports:
      -  5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=dibagi_app
    networks:
      - dibagi-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  dibagiApp:
    container_name: golangServer
    image: suryaasaputra/dibagi:2.0
    ports:
      - 80:8080
    depends_on:
      - postgresDB
    restart: on-failure
    environment:
      - DB_HOST=postgresDB
      - DB_NAME=dibagi_app
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - SECRET_KEY=s3CReT_672
      - SERVER_PORT=8080
      - BUCKET_NAME=dibagiin-data
      - STORAGE_PATH=https://storage.googleapis.com/dibagiin-data
      - BUCKET_SA_CR=dibagi-in-key.json
    networks:
      - dibagi-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: live@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - dibagi-network
    restart: unless-stopped

networks:
  dibagi-network:
    name: dibagi-network
