// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/donation": {
            "get": {
                "description": "Get list donation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation"
                ],
                "summary": "Get All Donation",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "availability",
                        "name": "available",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.GetDonationsResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Create new donation",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation"
                ],
                "summary": "Create Donation",
                "parameters": [
                    {
                        "description": "Donation data",
                        "name": "donation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateDonationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.CreateDonationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/donation/request": {
            "get": {
                "description": "Get all submitted donation request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation Request"
                ],
                "summary": "Get All Submitted Donation Request",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.GetDonationRequestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/donation/request/{donationRequest_id}": {
            "delete": {
                "description": "Cancel Send donation request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation Request"
                ],
                "summary": "Cancel Send Donation Request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Donation Request ID",
                        "name": "donationRequest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/donation/{donation_id}": {
            "get": {
                "description": "Get donation detail by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation"
                ],
                "summary": "Get Donation Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Donation ID",
                        "name": "donation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.GetDonationsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "Edit donation detail by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation"
                ],
                "summary": "Edit Donation Detail",
                "parameters": [
                    {
                        "description": "Donation data",
                        "name": "donation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EditDonationRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Donation ID",
                        "name": "donation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.EditDonationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete donation  by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation"
                ],
                "summary": "Delete Donation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Donation ID",
                        "name": "donation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/donation/{donation_id}/request": {
            "post": {
                "description": "Send request to claim donation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation Request"
                ],
                "summary": "Send Donation Request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Donation ID",
                        "name": "donation_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Donation request body",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateDonationRequestRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.CreateDonationRequestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "User Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.LoginUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/notification": {
            "get": {
                "description": "Get all user notification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Get All  Notification",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetNotificationResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "User Account Registration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "Register User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.CreateUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/request": {
            "get": {
                "description": "Get all recived donation request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation Request"
                ],
                "summary": "Get All Recived Donation Request",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.GetDonationRequestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/request/{donationRequest_id}": {
            "post": {
                "description": "Confirm request to claim donation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation Request"
                ],
                "summary": "Confirm Donation Request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Donation Request ID",
                        "name": "donationRequest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Reject donation request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Donation Request"
                ],
                "summary": "Reject Donation Request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Donation Request ID",
                        "name": "donationRequest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/user/{userId}": {
            "get": {
                "description": "Get user detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.GetUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/{user_name}": {
            "put": {
                "description": "Update user data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User",
                "parameters": [
                    {
                        "description": "Update User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EditUserRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "User Name",
                        "name": "user_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.EditUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User name",
                        "name": "user_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Response"
                        }
                    }
                }
            }
        },
        "/user/{user_name}/ProfilPhoto": {
            "put": {
                "description": "Set user profile photo",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Set Profile Photo",
                "parameters": [
                    {
                        "description": "Set Profile Photo User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SetProfilePhotoRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "user_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helpers.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.EditUserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helpers.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "error": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.CreateDonationRequest": {
            "type": "object"
        },
        "models.CreateDonationRequestRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Minta bang"
                }
            }
        },
        "models.CreateDonationRequestResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "donation_id": {
                    "type": "string"
                },
                "donator_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.CreateDonationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "models.CreateUserResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "phone_number": {
                    "type": "string"
                },
                "profil_photo_url": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "models.EditDonationRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "models.EditDonationResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "models.EditUserRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Jakarta"
                },
                "email": {
                    "type": "string",
                    "example": "user@mail.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "Full Name"
                },
                "gender": {
                    "type": "string",
                    "example": "Male"
                },
                "lat": {
                    "type": "number",
                    "example": -6.20104
                },
                "lng": {
                    "type": "number",
                    "example": 106.816666
                },
                "phone_number": {
                    "type": "string",
                    "example": "+62890123456"
                },
                "user_name": {
                    "type": "string",
                    "example": "user_name"
                }
            }
        },
        "models.EditUserResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "phone_number": {
                    "type": "string"
                },
                "profil_photo_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "models.GetDonationRequestResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "donation": {
                    "type": "object",
                    "properties": {
                        "created_at": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "location": {
                            "type": "string"
                        },
                        "photo_url": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        },
                        "updated_at": {
                            "type": "string"
                        },
                        "weight": {
                            "type": "integer"
                        }
                    }
                },
                "donation_id": {
                    "type": "string"
                },
                "donator": {
                    "type": "object",
                    "properties": {
                        "full_name": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "phone_number": {
                            "type": "string"
                        },
                        "profil_photo_url": {
                            "type": "string"
                        },
                        "user_name": {
                            "type": "string"
                        }
                    }
                },
                "donator_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "properties": {
                        "full_name": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "phone_number": {
                            "type": "string"
                        },
                        "profil_photo_url": {
                            "type": "string"
                        },
                        "user_name": {
                            "type": "string"
                        }
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.GetDonationsResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "donator": {
                    "type": "object",
                    "properties": {
                        "full_name": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "phone_number": {
                            "type": "string"
                        },
                        "profil_photo_url": {
                            "type": "string"
                        },
                        "user_name": {
                            "type": "string"
                        }
                    }
                },
                "id": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "location": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "requester_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "taker": {
                    "type": "object",
                    "properties": {
                        "full_name": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "phone_number": {
                            "type": "string"
                        },
                        "profil_photo_url": {
                            "type": "string"
                        },
                        "user_name": {
                            "type": "string"
                        }
                    }
                },
                "taker_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "models.GetNotificationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "donation": {
                    "type": "object",
                    "properties": {
                        "created_at": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "donator": {
                            "type": "object",
                            "properties": {
                                "full_name": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "string"
                                },
                                "phone_number": {
                                    "type": "string"
                                },
                                "profil_photo_url": {
                                    "type": "string"
                                },
                                "user_name": {
                                    "type": "string"
                                }
                            }
                        },
                        "id": {
                            "type": "string"
                        },
                        "lat": {
                            "type": "number"
                        },
                        "lng": {
                            "type": "number"
                        },
                        "location": {
                            "type": "string"
                        },
                        "photo_url": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        },
                        "updated_at": {
                            "type": "string"
                        },
                        "weight": {
                            "type": "integer"
                        }
                    }
                },
                "donation_id": {
                    "type": "string"
                },
                "donation_request": {
                    "type": "object",
                    "properties": {
                        "created_at": {
                            "type": "string"
                        },
                        "donation_id": {
                            "type": "string"
                        },
                        "donator_id": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        },
                        "requester": {
                            "type": "object",
                            "properties": {
                                "full_name": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "string"
                                },
                                "phone_number": {
                                    "type": "string"
                                },
                                "profil_photo_url": {
                                    "type": "string"
                                },
                                "user_name": {
                                    "type": "string"
                                }
                            }
                        },
                        "status": {
                            "type": "string"
                        },
                        "updated_at": {
                            "type": "string"
                        },
                        "user_id": {
                            "type": "string"
                        }
                    }
                },
                "donation_request_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "properties": {
                        "full_name": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "phone_number": {
                            "type": "string"
                        },
                        "profil_photo_url": {
                            "type": "string"
                        },
                        "user_name": {
                            "type": "string"
                        }
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.GetUserResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "donation": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "created_at": {
                                "type": "string"
                            },
                            "description": {
                                "type": "string"
                            },
                            "donator": {
                                "type": "object",
                                "properties": {
                                    "full_name": {
                                        "type": "string"
                                    },
                                    "id": {
                                        "type": "string"
                                    },
                                    "phone_number": {
                                        "type": "string"
                                    },
                                    "profil_photo_url": {
                                        "type": "string"
                                    },
                                    "user_name": {
                                        "type": "string"
                                    }
                                }
                            },
                            "id": {
                                "type": "string"
                            },
                            "location": {
                                "type": "string"
                            },
                            "photo_url": {
                                "type": "string"
                            },
                            "requester_id": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "status": {
                                "type": "string"
                            },
                            "taker": {
                                "type": "object",
                                "properties": {
                                    "full_name": {
                                        "type": "string"
                                    },
                                    "id": {
                                        "type": "string"
                                    },
                                    "phone_number": {
                                        "type": "string"
                                    },
                                    "profil_photo_url": {
                                        "type": "string"
                                    },
                                    "user_name": {
                                        "type": "string"
                                    }
                                }
                            },
                            "taker_id": {
                                "type": "string"
                            },
                            "title": {
                                "type": "string"
                            },
                            "updated_at": {
                                "type": "string"
                            },
                            "weight": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "profil_photo_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "models.LoginUserResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "login_time": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "profil_photo_url": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "models.SetProfilePhotoRequest": {
            "type": "object"
        },
        "models.UserLoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "tes@mail.com"
                },
                "password": {
                    "type": "string",
                    "example": "pass1234"
                }
            }
        },
        "models.UserRegisterRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Jakarta"
                },
                "email": {
                    "type": "string",
                    "example": "user@mail.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "Full Name"
                },
                "gender": {
                    "type": "string",
                    "example": "Male"
                },
                "lat": {
                    "type": "number",
                    "example": -6.20104
                },
                "lng": {
                    "type": "number",
                    "example": 106.816666
                },
                "password": {
                    "type": "string",
                    "example": "pass1234"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+62890123456"
                },
                "user_name": {
                    "type": "string",
                    "example": "user_name"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
